apiVersion: apps/v1
kind: Deployment
metadata:
  name: lana-bot-deployment
  namespace: lanabot-dev-ns
  labels:
    microservice: lana-bot
    project: lanabot-project
    env: dev
    release: v1.0
spec:
  replicas: 2
  selector:
    matchLabels:
      microservice: lana-bot
  template:
    metadata:
      labels:
        microservice: lana-bot
        project: lanabot-project
        env: dev
        release: v1.0
    spec:
      containers:
      - name: lana-bot-docker-container
        image: lanabot_image:tag
        ports:
        - containerPort: 8443
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
