apiVersion: apps/v1
kind: Deployment
metadata:
  name: lana-bot-deployment
  namespace: lanabot-ns
  labels:
    microservice: lanabot-microservice
    env: dev
    release: v1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      microservice: lanabot-microservice
  template:
    metadata:
      labels:
        microservice: lanabot-microservice
        env: dev
        release: v1.0
    spec:
      containers:
      - name: lanabot-docker-container
        image: lanabot_img:tag
        ports:
        - containerPort: 8443
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 300m
            memory: 300Mi
